In [57]:
import pandas as pd

In [58]:
df = pd.read_csv("D:\CSV files\movies.csv")

In [59]:
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [60]:
selected_feature = ["genres","keywords","tagline","title","director"]

In [61]:
df1 = df[["genres","keywords","tagline","title","cast","director"]]

In [62]:
df1.head()

genres  \
0  Action Adventure Fantasy Science Fiction   
1                  Adventure Fantasy Action   
2                    Action Adventure Crime   
3               Action Crime Drama Thriller   
4          Action Adventure Science Fiction   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   
2         spy based on novel secret agent sequel mi6   
3  dc comics crime fighter terrorist secret ident...   
4  based on novel mars medallion space travel pri...   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                                cast           director  
0  Sam Worthington Zoe Saldana Sigourney Weaver S...      James Cameron  
1  Johnny Depp Orlando Bloom Keira Knightley Stel...     Gore Verbinski  
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...         Sam Mendes  
3  Christian Bale Michael Caine Gary Oldman Anne ...  Christopher Nolan  
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...     Andrew Stanton

In [63]:
df1.shape

(4803, 6)

In [64]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   genres    4775 non-null   object
 1   keywords  4391 non-null   object
 2   tagline   3959 non-null   object
 3   title     4803 non-null   object
 4   cast      4760 non-null   object
 5   director  4773 non-null   object
dtypes: object(6)
memory usage: 225.3+ KB


In [65]:
df1.isnull().sum()

genres       28
keywords    412
tagline     844
title         0
cast         43
director     30
dtype: int64

In [66]:
"Action Adventure Fantasy Science Fiction	culture clash future space war space colony so...	Enter the World of Pandora.	Avatar	James Cameron"

'Action Adventure Fantasy Science Fiction\tculture clash future space war space colony so...\tEnter the World of Pandora.\tAvatar\tJames Cameron'

In [67]:
df1 = df1.fillna(" ")

In [68]:
df1.isnull().sum()

genres      0
keywords    0
tagline     0
title       0
cast        0
director    0
dtype: int64

In [69]:
df1.head(1)

genres  \
0  Action Adventure Fantasy Science Fiction   

                                            keywords  \
0  culture clash future space war space colony so...   

                       tagline   title  \
0  Enter the World of Pandora.  Avatar   

                                                cast       director  
0  Sam Worthington Zoe Saldana Sigourney Weaver S...  James Cameron

In [70]:
 combined_feature = df1["genres"]+ " "+df1["keywords"]+ " "+df1["tagline"] + " "+df1["cast"]+ " "+df1["director"]

In [71]:
combined_feature[0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society Enter the World of Pandora. Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez James Cameron'

In [72]:
from sklearn.feature_extraction.text import  CountVectorizer

In [73]:
vectors =  CountVectorizer()

In [74]:
feature_vector = vectors.fit_transform(combined_feature)

In [75]:
feature_vector.shape

(4803, 17318)

In [76]:
feature_vector.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [77]:
vectors.get_feature_names_out()

array(['000', '007', '05', ..., 'zwigoff', 'zylka', '最后的舞者'], dtype=object)

In [78]:
len(vectors.get_feature_names_out())

17318

In [79]:
import difflib

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

In [81]:
similarity = cosine_similarity(feature_vector)
similarity

array([[1.        , 0.25253814, 0.10206207, ..., 0.        , 0.        ,
        0.        ],
       [0.25253814, 1.        , 0.10997148, ..., 0.05714286, 0.        ,
        0.        ],
       [0.10206207, 0.10997148, 1.        , ..., 0.        , 0.09072184,
        0.        ],
       ...,
       [0.        , 0.05714286, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.09072184, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [82]:
similarity[0]

array([1.        , 0.25253814, 0.10206207, ..., 0.        , 0.        ,
       0.        ])

In [83]:
len(similarity)

4803

In [84]:
similarity.shape

(4803, 4803)

In [85]:

movie = input("Enter a movie name :")

Enter a movie name : iron man 


In [100]:
movie


'iron man '

In [101]:
movie_list = df["title"].to_list()

In [102]:
best_match = difflib.get_close_matches(movie, movie_list) 

In [103]:
best_match

['Iron Man 3', 'Iron Man 2', 'Iron Man']

In [104]:
exact_match = best_match[0]

In [105]:
index_of_movie = df[df["title"]==exact_match].values[0][0]
index_of_movie

31

In [106]:
similarity[68][:100]


array([0.12700013, 0.1026316 , 0.06913011, 0.03335187, 0.12320822,
       0.06788442, 0.14089399, 0.33882261, 0.03592106, 0.13340747,
       0.1796053 , 0.05354796, 0.070447  , 0.06558258, 0.18215302,
       0.03279129, 0.33882261, 0.06913011, 0.11503946, 0.11810772,
       0.13576885, 0.05986843, 0.03225806, 0.02993422, 0.05679618,
       0.        , 0.32258065, 0.12903226, 0.16971106, 0.070447  ,
       0.12320822, 0.37518324, 0.06071767, 0.22953904, 0.        ,
       0.14664712, 0.13116517, 0.03456506, 0.16675934, 0.19674775,
       0.03225806, 0.15401028, 0.        , 0.13116517, 0.03666178,
       0.10182663, 0.22718473, 0.14980118, 0.070447  , 0.        ,
       0.06788442, 0.11973687, 0.12320822, 0.1000556 , 0.06788442,
       0.07184212, 0.15677236, 0.07838618, 0.03829198, 0.13116517,
       0.03592106, 0.13826023, 0.07332356, 0.03126527, 0.19354839,
       0.03335187, 0.03279129, 0.10369517, 1.        , 0.0547791 ,
       0.13116517, 0.08466675, 0.16395646, 0.        , 0.10776

In [107]:
final_match = list(enumerate(similarity[index_of_movie][:100]))
final_match

[(0, np.float64(0.21541010921383227)),
 (1, np.float64(0.2238141290858972)),
 (2, np.float64(0.10050378152592121)),
 (3, np.float64(0.1293016367670472)),
 (4, np.float64(0.149270358506633)),
 (5, np.float64(0.1315903389919538)),
 (6, np.float64(0.03413943709994595)),
 (7, np.float64(0.32839478871459254)),
 (8, np.float64(0.03481553119113957)),
 (9, np.float64(0.1293016367670472)),
 (10, np.float64(0.20889318714683744)),
 (11, np.float64(0.051899929610768204)),
 (12, np.float64(0.0682788741998919)),
 (13, np.float64(0.12712834523274563)),
 (14, np.float64(0.23539595453459988)),
 (15, np.float64(0.06356417261637282)),
 (16, np.float64(0.32839478871459254)),
 (17, np.float64(0.06700252101728081)),
 (18, np.float64(0.13937366833451514)),
 (19, np.float64(0.17170914210964275)),
 (20, np.float64(0.19738550848793068)),
 (21, np.float64(0.05802588531856595)),
 (22, np.float64(0.09379580992210838)),
 (23, np.float64(0.14506471329641488)),
 (24, np.float64(0.19266865889711313)),
 (25, np.float64

In [108]:
final_match = list(enumerate(similarity[index_of_movie]))
final_match

[(0, np.float64(0.21541010921383227)),
 (1, np.float64(0.2238141290858972)),
 (2, np.float64(0.10050378152592121)),
 (3, np.float64(0.1293016367670472)),
 (4, np.float64(0.149270358506633)),
 (5, np.float64(0.1315903389919538)),
 (6, np.float64(0.03413943709994595)),
 (7, np.float64(0.32839478871459254)),
 (8, np.float64(0.03481553119113957)),
 (9, np.float64(0.1293016367670472)),
 (10, np.float64(0.20889318714683744)),
 (11, np.float64(0.051899929610768204)),
 (12, np.float64(0.0682788741998919)),
 (13, np.float64(0.12712834523274563)),
 (14, np.float64(0.23539595453459988)),
 (15, np.float64(0.06356417261637282)),
 (16, np.float64(0.32839478871459254)),
 (17, np.float64(0.06700252101728081)),
 (18, np.float64(0.13937366833451514)),
 (19, np.float64(0.17170914210964275)),
 (20, np.float64(0.19738550848793068)),
 (21, np.float64(0.05802588531856595)),
 (22, np.float64(0.09379580992210838)),
 (23, np.float64(0.14506471329641488)),
 (24, np.float64(0.19266865889711313)),
 (25, np.float64

In [109]:
from operator import itemgetter

In [110]:
sorted_match = sorted(final_match, key=itemgetter(1,0),reverse=True)

In [111]:
sorted_match

[(31, np.float64(0.9999999999999999)),
 (79, np.float64(0.5903260526902472)),
 (68, np.float64(0.3751832396884334)),
 (26, np.float64(0.34391796971439736)),
 (46, np.float64(0.3302891295379082)),
 (16, np.float64(0.32839478871459254)),
 (7, np.float64(0.32839478871459254)),
 (4193, np.float64(0.32566947363946486)),
 (2357, np.float64(0.307578579243517)),
 (466, np.float64(0.2909286827258562)),
 (870, np.float64(0.28618190351607126)),
 (4276, np.float64(0.2791452631195413)),
 (182, np.float64(0.27695585470349865)),
 (4176, np.float64(0.27647061653842375)),
 (203, np.float64(0.27524094128159016)),
 (205, np.float64(0.2731154967995676)),
 (122, np.float64(0.2731154967995676)),
 (1191, np.float64(0.2718636239135185)),
 (2860, np.float64(0.2686866453119394)),
 (342, np.float64(0.26860765467512676)),
 (1086, np.float64(0.26482044885142486)),
 (2815, np.float64(0.26243194054073904)),
 (4401, np.float64(0.2611164839335468)),
 (511, np.float64(0.2586032735340944)),
 (505, np.float64(0.257563713

In [112]:
n = 0
for i in sorted_match:
    n+=1
    if n<6:
        index = (sorted_match[n][0])
        # print(index)
        print(df.iloc[index]["title"])

Iron Man 2
Iron Man
Captain America: Civil War
X-Men: Days of Future Past
The Avengers


In [113]:
df.iloc[79]["title"]

'Iron Man 2'